[workspace]
members = ["crates/*"]
resolver = "2"

[profile.dev]
panic = "abort"
lto = true

[profile.release]
panic = "abort"
lto = true

[workspace.package]
edition = "2021"
repository = "https://github.com/microsoft/windows-drivers-rs"
readme = "README.md"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
wdk = { path = "crates/wdk" }
wdk-alloc = { path = "crates/wdk-alloc" }
wdk-build = { path = "crates/wdk-build" }
wdk-macros = { path = "crates/wdk-macros" }
wdk-panic = { path = "crates/wdk-panic" }
wdk-sys = { path = "crates/wdk-sys" }
bindgen = "0.68.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
